dbfilename redis_queue.rdb
dir /home/je_7_/mi-erp-bench/config/pids
pidfile /home/je_7_/mi-erp-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/je_7_/mi-erp-bench/config/redis_queue.acl
